/**
 * CLAUDE.md 템플릿 생성기
 */

import type { ModelRole, ModelConfig, ProjectType } from '../types/index.js';
import { PROJECT_TYPE_CONFIGS } from '../types/index.js';

export interface ClaudeMdOptions {
  projectName: string;
  models: Record<ModelRole, ModelConfig>;
  // 프로젝트 커스터마이징
  projectType?: ProjectType;
  projectDescription?: string;
  techStack?: string[];
  customConventions?: string[];
}

/**
 * CLAUDE.md 파일 내용 생성
 */
export function generateClaudeMd(options: ClaudeMdOptions): string {
  const {
    projectName,
    models,
    projectType,
    projectDescription,
    techStack,
    customConventions,
  } = options;

  // 프로젝트 타입 설정 가져오기
  const typeConfig = projectType ? PROJECT_TYPE_CONFIGS[projectType] : null;

  // 기술 스택 결정 (사용자 지정 > 타입 기본값)
  const finalTechStack = techStack && techStack.length > 0
    ? techStack
    : typeConfig?.techStack || [];

  // 컨벤션 결정 (사용자 지정 + 타입 기본값)
  const finalConventions = [
    ...(typeConfig?.conventions || []),
    ...(customConventions || []),
  ];

  // 프로젝트 설명 결정
  const finalDescription = projectDescription || typeConfig?.description || '';

  // CLAUDE.md 생성
  let content = `# ${projectName}

`;

  // 프로젝트 설명
  if (finalDescription) {
    content += `> ${finalDescription}

`;
  }

  // 프로젝트 타입 표시
  if (projectType && projectType !== 'custom') {
    content += `**Project Type**: ${projectType}

`;
  }

  // 기술 스택
  if (finalTechStack.length > 0) {
    content += `## Tech Stack
${finalTechStack.map(t => `- ${t}`).join('\n')}

`;
  }

  // 개발 컨벤션
  if (finalConventions.length > 0) {
    content += `## Development Conventions
${finalConventions.map(c => `- ${c}`).join('\n')}

`;
  }

  // Task Master 연동
  content += `## Task Master AI
@./.taskmaster/CLAUDE.md

### Model Configuration
| Role | Provider | Model |
|------|----------|-------|
| Main | ${models.main.provider} | ${models.main.model} |
| Research | ${models.research.provider} | ${models.research.model} |
| Fallback | ${models.fallback.provider} | ${models.fallback.model} |

### Quick Commands
\`\`\`bash
task-master list              # 작업 목록
task-master next              # 다음 작업
task-master show <id>         # 작업 상세
task-master set-status --id=<id> --status=done  # 완료
\`\`\`

## Workflow
1. \`task-master next\` - 다음 작업 확인
2. 코드 구현
3. \`task-master update-subtask --id=<id> --prompt="진행 상황"\`
4. \`task-master set-status --id=<id> --status=done\`

---
*Generated by @successbank/taskmaster-kit*
`;

  return content;
}
