/**
 * .env 템플릿 생성기
 */

import type { Provider } from '../types/index.js';

export interface EnvTemplateOptions {
  apiKeys: Partial<Record<Provider, string>>;
}

/**
 * .env 파일 내용 생성
 */
export function generateEnvFile(options: EnvTemplateOptions): string {
  const { apiKeys } = options;

  const lines: string[] = [
    '# Task Master AI - API Keys',
    '# Generated by @successbank/taskmaster-kit',
    '',
    '# API Keys (Required to enable respective provider)',
  ];

  // Anthropic
  if (apiKeys.anthropic) {
    lines.push(`ANTHROPIC_API_KEY="${apiKeys.anthropic}"`);
  } else {
    lines.push('# ANTHROPIC_API_KEY="sk-ant-..."');
  }

  // OpenAI
  if (apiKeys.openai) {
    lines.push(`OPENAI_API_KEY="${apiKeys.openai}"`);
  } else {
    lines.push('# OPENAI_API_KEY="sk-proj-..."');
  }

  // Google
  if (apiKeys.google) {
    lines.push(`GOOGLE_API_KEY="${apiKeys.google}"`);
  } else {
    lines.push('# GOOGLE_API_KEY="AIza..."');
  }

  // Perplexity
  if (apiKeys.perplexity) {
    lines.push(`PERPLEXITY_API_KEY="${apiKeys.perplexity}"`);
  } else {
    lines.push('# PERPLEXITY_API_KEY="pplx-..."');
  }

  // Optional providers
  lines.push('');
  lines.push('# Optional Providers');

  if (apiKeys.mistral) {
    lines.push(`MISTRAL_API_KEY="${apiKeys.mistral}"`);
  } else {
    lines.push('# MISTRAL_API_KEY=""');
  }

  if (apiKeys.xai) {
    lines.push(`XAI_API_KEY="${apiKeys.xai}"`);
  } else {
    lines.push('# XAI_API_KEY=""');
  }

  if (apiKeys.openrouter) {
    lines.push(`OPENROUTER_API_KEY="${apiKeys.openrouter}"`);
  } else {
    lines.push('# OPENROUTER_API_KEY=""');
  }

  lines.push('');

  return lines.join('\n');
}
